<?php

/**
 * Implements hook_graphapi_settings_form().
 */
function graph_phyz_graphapi_settings_form($values) {
  $engine = 'graph_phyz';
  $values += array(
    'menu' => TRUE,
    'showLinks' => FALSE,
    'background-color' => 'white',
    'graph' => array(
      'animate' => TRUE,
      'background-color' => 'grey',
      'height' => '800',
      'menu' => TRUE,
      'randomize' => TRUE,
      'rankType' => 'TopBottom',
      'rankDepth' => 2,
      'showLinks' => FALSE,
      'width' => '800',
    ),
    'physics' => array(
      'showForces' => FALSE,
      'applyAttractToCenter' => TRUE,
      'applyBoundingBox' => FALSE,
      'applyBoxOverlap' => FALSE,
      'applyCoulombsLaw' => TRUE,
      'applyDamping' => TRUE,
      'applyHookesLaw' => TRUE,
      'applyCompass' => FALSE,
    ),
  );
  $form[$engine] = array(
    '#title' => t('Graph Phyz settings'),
    '#type' => 'fieldset',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE,
  );
  $form[$engine]['menu'] = array(
    '#title' => t('Show menu'),
    '#type' => 'checkbox',
    '#default_value' => $values['menu'],
  );
  $form[$engine]['showLinks'] = array(
    '#title' => t('Show link labels'),
    '#type' => 'checkbox',
    '#default_value' => $values['showLinks'],
  );
  return $form;
}

/**
 * Implements hook_graphapi_formats().
 */
function graph_phyz_graphapi_formats() {
  return array(
    'graph_phyz' => t('Graph Phyz'),
  );
}

function graph_phyz_theme() {
  return array(
    'views-graphapi-style-graph-phyz' => array(
      'variables' => array(
        'graph' => NULL,
        'config' => NULL,
      ),
    ),
  );
}

function graph_phyz_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'graph_phyz'),
  );
}

//TODO: move to graph_phyz.module
function template_preprocess_views_graphapi_style_graph_phyz(&$vars) {
  _views_graphapi_style_build_graph_data($vars);

  $config = $vars['settings'];
  $config = $config + graphapi_default_config();
  $vars["xml"] = theme('graphapi_container', array('graph' => $vars['graph'], 'config' => $config));
}
